name: Build Docker Image for ROS 2 CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-jazzy:
    name: Build (Jazzy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: ./jazzy
          platforms: linux/amd64
          outputs: type=image,push=true
          tags: ghcr.io/whill-labs/ci/ros:jazzy-desktop-full
